pipeline {
    agent any

    environment {
        PYTHON = 'C:\\Program Files\\Python313\\python.exe'
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {

        stage('Build') {
            steps {
                bat '"%PYTHON%" -m py_compile sources/add2vals.py sources/calc.py'
            }
        }

        stage('Test') {
            steps {
                bat 'if not exist test-reports mkdir test-reports'
                bat '"%PYTHON%" -m pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }

            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                bat 'if exist "C:\\JenkinsBuild\\myapp" rmdir /S /Q "C:\\JenkinsBuild\\myapp"'

                bat '"%PYTHON%" -m PyInstaller --clean --noconfirm --name myapp --distpath "C:\\JenkinsBuild" sources/add2vals.py'

                bat 'if exist "C:\\JenkinsBuild\\myapp.zip" del /F /Q "C:\\JenkinsBuild\\myapp.zip"'

                bat 'powershell -Command "Compress-Archive -Path ''C:\\JenkinsBuild\\myapp'' -DestinationPath ''C:\\JenkinsBuild\\myapp.zip'' -Force"'

                bat 'copy /Y "C:\\JenkinsBuild\\myapp.zip" "myapp.zip"'
            }

            post {
                success {
                    archiveArtifacts artifacts: 'myapp.zip', allowEmptyArchive: false
                }
            }
        }
    }
}