pipeline {
    agent any

    options {
        skipStagesAfterUnstable()
    }

    environment {
        PYTHON = 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\\python.exe'
    }

    stages {

        stage('Build') {
            steps {
                bat '"%PYTHON%" -m py_compile sources/add2vals.py sources/calc.py'
            }
        }

        stage('Test') {
            steps {
                bat '"%PYTHON%" -m pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
            }
            }
        }

        stage('Deliver') {
            steps {
                bat '"%PYTHON%" -m PyInstaller --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals.exe'
                }
            }
        }
    }
}