pipeline {
    agent any

    environment {
        PYTHON = 'C:\\Users\\TEJAASHRI K\\AppData\\Local\\Programs\\Python\\Python313\\python.exe'
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {

        stage('Build') {
            steps {
                bat '"%PYTHON%" -m py_compile sources/add2vals.py sources/calc.py'
            }
        }

        stage('Test') {
            steps {
                bat 'if not exist test-reports mkdir test-reports'
                bat '"%PYTHON%" -m pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }

            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                bat '"%PYTHON%" -m PyInstaller --onefile sources/add2vals.py'
            }

            post {
                success {
                    archiveArtifacts 'dist/add2vals.exe'
                }
            }
        }
    }
}